/*
 * ADC_Config.h
 */
#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_

/* The glove reads each channel synchronously before classification. */
#define ADC_TRIGGERING_MODE SOFTWARE_TRIGGER
#define ADC_AUTO_TRIGGER_PIN ADC_0
#define ADC_READING_NO_OF_BITS _16_BIT_MODE
#define ADC_READING_TECHNIQUE BOOLING_MODE

#define ADC_0_CONNECTION {PORT_A, PIN_0}
#define ADC_1_CONNECTION {PORT_A, PIN_1}
#define ADC_2_CONNECTION {PORT_A, PIN_2}
#define ADC_3_CONNECTION {PORT_A, PIN_3}
#define ADC_4_CONNECTION {PORT_A, PIN_4}
#define ADC_5_CONNECTION {PORT_A, PIN_5}
#define ADC_6_CONNECTION {PORT_A, PIN_6}
#define ADC_7_CONNECTION {PORT_A, PIN_7}

#endif /* MCAL_ADC_ADC_CONFIG_H_ */
